<?php
// Start get Currency
$barcodeno = 19027867676;
$user_detail[] = array();
$user_detail['euser_fullname'] = 'Rio Bahtiar';
$user_detail['euser_address'] = 'Jalan Kaliurang';
$user_detail['euser_barcode'] = $barcodeno;
$user_detail['euser_meta_type'] = 'author_type';
$user_string = 'User String';
$user_type = 'User Type';
$string_mid_conf = 'String Mid Conf';
$string_post_conf = 'String Post Conf';
$string_dinner = 'Yes';
$idr_total = 6999000;




/// ======= FPDF BLOCK ============ ///

    require('eticket.php');
    $title = 'IUFRO ACACIA CONFERENCE 2017';
// Setting Page
    $pdf = new PDF_Code128();
    $pdf->AddPage('P', 'A4');
// Barcode
    $pdf->Cell(28, 117, '', 1, 0, 'C');
    $pdf->Rotate(90, 88, 120);
    $pdf->Code128(100, 46, $barcodeno, 90, 15);
    $pdf->Rotate(0);
    $pdf->SetFont('Arial', 'B', 14);
    $pdf->RotatedText(36, 80, 'ID ' . $barcodeno, 90);
    $pdf->Cell(160, 30, '', 1, 0, 'C');
    $pdf->Image('http://staging.iufroacacia2017.com/wp-content/uploads/2016/06/logo.png', 146, 17, 50);
    $pdf->SetFont('Arial', 'B', 15);
    $pdf->SetXY(45, 23);
    $pdf->Write(5, $title);
    $pdf->SetXY(39, 11);
    $pdf->SetFont('Arial', '', 12);
    $pdf->Write(5, 'EVENT');
    $pdf->SetXY(38, 40);
    $pdf->Cell(80, 30, '', 1, 0, 'C');
    $pdf->Cell(80, 30, '', 1, 0, 'C');
    $pdf->SetXY(39, 41);
    $pdf->SetFont('Arial', '', 12);
    $pdf->Write(5, 'DATE');
    $pdf->SetXY(49, 52);
    $pdf->Write(5, 'July 24, 2017 - July 28, 2017');
    $pdf->SetXY(119, 41);
    $pdf->Write(5, 'VENUE');
    $pdf->SetXY(128, 47);
    $pdf->SetFont('Arial', 'B', 12);
    $pdf->Write(5, 'The Alana Yogyakarta Hotel');
    $pdf->SetXY(133, 52);
    $pdf->Write(5, 'and Convention Center');
    $pdf->SetFont('Arial', '', 12);
    $pdf->SetXY(123, 58);
    $pdf->Write(5, 'Jalan Palagan Tentara Pelajar Km 15,');
    $pdf->SetXY(125, 64);
    $pdf->Write(5, 'Pakem, Sleman, Yogyakarta 55582');
    $pdf->SetXY(38, 70);
    $pdf->Cell(160, 57, '', 1, 0, 'C');

    if ($user_detail['euser_meta_type'] == "participant_type") {
        $user_type = "Participant";
    } elseif ($user_detail['euser_meta_type'] == "author_type") {
        $user_type = "Author";
    } else {
        $user_type = "Free Account";
    }

    $pdf->SetXY(39, 71);
    $pdf->Write(5, 'DETAILS');
    $pdf->SetXY(45, 77);
    $pdf->Write(5, 'Full Name : ' . $user_detail['euser_fullname']);
    $pdf->SetXY(45, 83);
    $pdf->Write(5, 'Address : ' . $user_detail['euser_address']);
    $pdf->SetXY(45, 89);
    $pdf->Write(5, 'Membership Type : ' . $user_string . ' ' . $user_type);
    $pdf->SetXY(45, 95);
    $pdf->Write(5, 'Field Trip :');
    $pdf->SetXY(47, 102);
    $pdf->Write(5, ' ~ Mid Conference : ' . $string_mid_conf);
    $pdf->SetXY(47, 108);
    $pdf->Write(5, ' ~ Post Conference : ' . $string_post_conf);
    $pdf->SetXY(45, 114);
    $pdf->Write(5, ' Conference Dinner : ' . $string_dinner);
    $pdf->SetXY(45, 120);
    $pdf->Write(5, ' Payment : IDR' . $idr_total);

    $pdf->SetXY(50, 200);
    $pdf->SetFont('Arial', '', 10);
    $pdf->Write(5, 'generated by system on ' . date('Y-m-d H:i:s T'));
    $pdf->Image('http://staging.iufroacacia2017.com/wp-content/uploads/2016/08/paid.png', 164, 73, 30);

    // $filename = $upload_dir['basedir'] . "/dumpticket/iufro2017_ticket_" . $barcodeno . ".pdf";
    // $pdf->Output($filename, 'F');
    $pdf->Output();

/// ======= END FPDF ============ ///

